theme: jekyll-theme-minimal
title: Andrew Taylor
logo: 
description:
  Georgia Tech MS Analytics | BS Industrial Engineering
  <br>
  Data Science Graduate Intern @ Kabbage
  <br>
  Ex-Consultant
  <br>
  Austinite
  <br><br>
  <a href="https://www.linkedin.com/in/andrew-taylor-6a77b932/">Visit my LinkedIn Profile<\a>
  <br>
  astaylor.m92@gmail.com | 678.628.4604
